version: '3.5'

networks:
  laravel:
    name: ${PROJECT_NAME}_network

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "America/Los_Angeles"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    container_name: ${PROJECT_NAME}_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
  npm:
    image: node:13.7.0-slim
    container_name: ${PROJECT_NAME}_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  npx:
    image: node:13.7.0-slim
    container_name: ${PROJECT_NAME}_npx
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npx' ]
    networks:
      - laravel
  artisan:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: ${PROJECT_NAME}_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - laravel
volumes:
  mysql_data:
    name: ${PROJECT_NAME}_volume_001
    driver: "local"
