version: '3.5'

networks:
  laravel:
    name: ${PROJECT_NAME}_network

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}_nginx
    working_dir: /var/www
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "America/Los_Angeles"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

volumes:
  mysql_data:
    name: ${PROJECT_NAME}_volume_001
    driver: "local"
